apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103
  selector:
    app: ftps
  ports:
    - port: 21
      name: https
      protocol: TCP
      targetPort: 21
    - port: 3001
      name: passv-port
      protocol: TCP
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      name: ftps
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ftps
          imagePullPolicy: Never
          ports:
            - containerPort: 21
            - containerPort: 3001

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ftps
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/var/lib/ftp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
