apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  label:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePolicy: Never
          ports:
            - containerPort: 80

